name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    
    - name: Build
      run: cargo build --verbose 

    - name: Generate many-to-many transactions
      run: |
        cargo build --release
        ./target/release/generate pattern -y m2m -t 100 -c 0.6 -o ./test.json
